name: Update YXL Status

on:
  schedule:
    - cron: '*/10 * * * *' # 10분마다 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python yxl.py # yxl.py 실행
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add status.json
          git commit -m "Update YXL status" || exit 0
          git push
